CREATE DATABASE ESports_Fantasy
GO

CREATE TABLE tblRANK (
RankID INT IDENTITY(1,1) PRIMARY KEY,
RankName VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblPLAYER(
PlayerID INT IDENTITY(1,1) PRIMARY KEY,
PlayerName VARCHAR(100),
TagLine VARCHAR(20),
RankID INT FOREIGN KEY REFERENCES tblRANK(RankID) NOT NULL
)
GO

CREATE TABLE tblTEAMS (
TeamID INT IDENTITY(1,1) PRIMARY KEY,
TeamName VARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblCOACH (
CoachID INT IDENTITY(1,1)PRIMARY KEY,
PlayerID INT FOREIGN KEY REFERENCES tblPLAYER(PlayerID) NOT NULL,
TeamID INT FOREIGN KEY REFERENCES tblTEAMS(TeamID) NOT NULL
)
GO

CREATE TABLE tblCHARACTER (
CharacterID INT IDENTITY(1,1) PRIMARY KEY,
CharacterName VARCHAR(200) NOT NULL,
CharacterDescr VARCHAR(200) NOT NULL,
Ability1 VARCHAR(50),
Ability2 VARCHAR(50),
Ability3 VARCHAR(50),
Ultimate VARCHAR(50)
)
GO

CREATE TABLE tblACT (
ActID INT IDENTITY(1,1) PRIMARY KEY,
ActName VARCHAR(100)
)
GO

CREATE TABLE tblEPISODE (
EpisodeID INT IDENTITY(1,1) PRIMARY KEY,
EpisodeName VARCHAR(100),
ActID INT FOREIGN KEY REFERENCES tblACT(ActID) NOT NULL,
)
GO

CREATE TABLE tblMAP (
MapID INT IDENTITY(1,1) PRIMARY KEY,
MapName VARCHAR(100)
)
GO

CREATE TABLE tblMATCH_TYPE (
MatchTypeID INT IDENTITY(1,1) PRIMARY KEY,
MatchTypeName VARCHAR(100)
)
GO

CREATE TABLE tblROUND (
RoundID INT IDENTITY(1,1) PRIMARY KEY,
RoundName VARCHAR(100)
)
GO

CREATE TABLE tblMATCH (
MatchID INT IDENTITY(1,1) PRIMARY KEY,
MatchName VARCHAR(100),
MapID INT FOREIGN KEY REFERENCES tblMAP(MapID) NOT NULL,
EpisodeID INT FOREIGN KEY REFERENCES tblEPISODE(EpisodeID) NOT NULL,
MatchTypeID INT FOREIGN KEY REFERENCES tblMATCH_TYPE(MatchTypeID) NOT NULL,
isCompleted BIT
)
GO

CREATE TABLE tblCOACH_MATCH (
CoachMatchID INT IDENTITY(1,1) PRIMARY KEY,
CoachID INT FOREIGN KEY REFERENCES  tblCOACH(CoachID) NOT NULL,
MatchID INT FOREIGN KEY REFERENCES tblMATCH(MatchID) NOT NULL
)
GO

CREATE TABLE tblROUND_MATCH_PLAYER (
RoundMatchPlayerID INT IDENTITY(1,1) PRIMARY KEY,
RoundID INT FOREIGN KEY REFERENCES tblROUND(RoundID) NOT NULL,
PlayerID INT FOREIGN KEY REFERENCES tblPLAYER(PlayerID) NOT NULL,
MatchID INT FOREIGN KEY REFERENCES tblMATCH(MatchID) NOT NULL,
Score INT,
Kills INT,
Deaths INT,
Assists INT,
Plants INT,
Defuses INT
)
GO

CREATE TABLE tblPLAYER_MATCH_TEAMS (
PlayerMatchTeamsID INT IDENTITY(1,1) PRIMARY KEY,
PlayerID INT FOREIGN KEY REFERENCES tblPLAYER(PlayerID) NOT NULL,
CharacterID INT FOREIGN KEY REFERENCES tblCHARACTER(CharacterID) NOT NULL,
TeamID INT FOREIGN KEY REFERENCES tblTEAMS(TeamID) NOT NULL,
MatchID INT FOREIGN KEY REFERENCES tblMatch(MatchID) NOT NULL,
TotalScore INT,
TotalKills INT,
TotalDeaths INT,
TotalAssists INT
)
GO