SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblEPISODE](
	[EpisodeID] [int] IDENTITY(1,1) NOT NULL,
	[EpisodeName] [varchar](100) NULL,
	[ActID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblEPISODE] ADD PRIMARY KEY CLUSTERED 
(
	[EpisodeID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblEPISODE]  WITH CHECK ADD FOREIGN KEY([ActID])
REFERENCES [dbo].[tblACT] ([ActID])
GO
