SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMATCH](
	[MatchID] [int] IDENTITY(1,1) NOT NULL,
	[MatchName] [varchar](100) NULL,
	[MapID] [int] NOT NULL,
	[EpisodeID] [int] NOT NULL,
	[MatchTypeID] [int] NOT NULL,
	[isCompleted] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblMATCH] ADD PRIMARY KEY CLUSTERED 
(
	[MatchID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblMATCH]  WITH CHECK ADD FOREIGN KEY([EpisodeID])
REFERENCES [dbo].[tblEPISODE] ([EpisodeID])
GO
ALTER TABLE [dbo].[tblMATCH]  WITH CHECK ADD FOREIGN KEY([MapID])
REFERENCES [dbo].[tblMAP] ([MapID])
GO
ALTER TABLE [dbo].[tblMATCH]  WITH CHECK ADD FOREIGN KEY([MatchTypeID])
REFERENCES [dbo].[tblMATCH_TYPE] ([MatchTypeID])
GO
