SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMATCH_TYPE](
	[MatchTypeID] [int] IDENTITY(1,1) NOT NULL,
	[MatchTypeName] [varchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblMATCH_TYPE] ADD PRIMARY KEY CLUSTERED 
(
	[MatchTypeID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
