SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblMAP](
	[MapID] [int] IDENTITY(1,1) NOT NULL,
	[MapName] [varchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblMAP] ADD PRIMARY KEY CLUSTERED 
(
	[MapID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
