SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblPLAYER](
	[PlayerID] [int] IDENTITY(1,1) NOT NULL,
	[PlayerName] [varchar](100) NULL,
	[TagLine] [varchar](20) NULL,
	[RankID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblPLAYER] ADD PRIMARY KEY CLUSTERED 
(
	[PlayerID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblPLAYER]  WITH CHECK ADD FOREIGN KEY([RankID])
REFERENCES [dbo].[tblRANK] ([RankID])
GO
