SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblROUND_MATCH_PLAYER](
	[RoundMatchPlayerID] [int] IDENTITY(1,1) NOT NULL,
	[RoundID] [int] NOT NULL,
	[PlayerID] [int] NOT NULL,
	[MatchID] [int] NOT NULL,
	[Score] [int] NULL,
	[Kills] [int] NULL,
	[Deaths] [int] NULL,
	[Assists] [int] NULL,
	[Plants] [int] NULL,
	[Defuses] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblROUND_MATCH_PLAYER] ADD PRIMARY KEY CLUSTERED 
(
	[RoundMatchPlayerID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblROUND_MATCH_PLAYER]  WITH CHECK ADD FOREIGN KEY([MatchID])
REFERENCES [dbo].[tblMATCH] ([MatchID])
GO
ALTER TABLE [dbo].[tblROUND_MATCH_PLAYER]  WITH CHECK ADD FOREIGN KEY([PlayerID])
REFERENCES [dbo].[tblPLAYER] ([PlayerID])
GO
ALTER TABLE [dbo].[tblROUND_MATCH_PLAYER]  WITH CHECK ADD FOREIGN KEY([RoundID])
REFERENCES [dbo].[tblROUND] ([RoundID])
GO
