SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblROUND](
	[RoundID] [int] IDENTITY(1,1) NOT NULL,
	[RoundName] [varchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblROUND] ADD PRIMARY KEY CLUSTERED 
(
	[RoundID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
