SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblRANK](
	[RankID] [int] IDENTITY(1,1) NOT NULL,
	[RankName] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblRANK] ADD PRIMARY KEY CLUSTERED 
(
	[RankID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
